### ISSUE TITLE
Bevy the book

### ISSUE THREAD

**Issue by peter-kehl** [lborb/book#20]
Hi Glyn,

Suggest adding https://bevyengine.org/learn/book/introduction/. Up to you whether for Unofficial or Application.

Thanks in advance.

**Comment by glyn** [comment]
Thanks @peter-kehl. That doesn't _appear_ to be in mdbook format (although it's similar), in which case it should go in "Books in Other Formats". Can you tell whether it is in mdbook format? E.g. can you find the source for the book?

**Comment by peter-kehl** [comment]
Thx.
