### ISSUE TITLE
FFI books

### ISSUE THREAD

**Issue by ssokolow** [lborb/book#22]
I don't have time to do a PR right now (partly because I don't have time to investigate whether they fully meet the criteria for inclusion in this list), but these two may be good additions:

* [The (unofficial) Rust FFI Guide](https://michael-f-bryan.github.io/rust-ffi-guide/overview.html)
* [The Rust FFI Omnibus](http://jakegoulding.com/rust-ffi-omnibus/)

**Comment by glyn** [comment]
Thanks @ssokolow!

**Comment by ssokolow** [comment]
Thanks for the quick response but I did notice two mistakes.

1. You accidentally used the Rust FFI Omnibus URL for both entries.
2. "The (unofficial) Rust FFI Guide" is the title of the whole mdBook, as seen in the `<title>` and the on-hover text in the header on every page, but you used "Using Unsafe for Fun and Profit", which is the long title of just the "Overview" chapter.

Now that I know they're eligible, would you like me to whip up a quick PR to fix those?

**Comment by glyn** [comment]
Yes, please. Sorry about that.
