### ISSUE TITLE
Consider distributing other format books among the mdbook format books

### ISSUE THREAD

**Issue by glyn** [lborb/book#29]
Rather than putting them out of order in their own chapter, perhaps we should use some other way of indicating non-mdbook books which could then be listed in the appropriate chapters.

@kw-fn WDYT?

**Comment by kw-fn** [comment]
I hadn't looked that closely to notice whether indexing the different formats makes a difference in information retrieval. I think that several shorter lists are better than long lists though that might also contribute to information hiding.

**Comment by kw-fn** [comment]
Personally I prefer topic-level organization over format-level.

**Comment by glyn** [comment]
Ok, we are agreed.

While we are re-organising the book, I wonder if it would be worth mixing the official books in among the rest, again organising by topics?

I would like to find some way of indicating which books are official and which are "other format" because I don't want the book to descend into a list of any old Rust websites as that wouldn't really be in the spirit of a "book of books". My main purpose in creating the book was to collect together all the (nice) books which I kept bumping into randomly.

**Comment by glyn** [comment]
Actually, I might even consider finessing the distinction between mdbook format and other (similar) formats as that is really a detail from the readers' perspective. We just need to avoid including print books and completely non-book formats, I think.
