### ISSUE TITLE
Should branch to other sources?

### ISSUE THREAD

**Issue by danipoma** [lborb/book#46]
Hello,

I don't know whether you add it or not - it is not a book, but it helps to visualize memory model and form data structure based on your requirements.

I am talking about https://github.com/usagi/rust-memory-container-cs

Since I don't know if you see this repo/book as a reference to only literacy sources or as an index containing knowledge about rust. I perceive it as an index.

Kinda hard to distinct goal of this repo since it also includes docs of rust apps themselves ([Amethyst Game Engine](https://book.amethyst.rs/stable/) or [rg3d Cheat/Guide Book](https://rg3d-book.github.io/)), which I believe shouldn't be here since by that logic you could include whole [awesome-rust](https://github.com/rust-unofficial/awesome-rust) into this book, but then useful information (how-tos, rust memory model etc.) would get shadowed - therefore such apps should be mentioned in [awesome-rust](https://github.com/rust-unofficial/awesome-rust) instead. 

When this book will get bigger - I see it that you accept any source - you probably also have to trim information based on their qualities.

**Comment by glyn** [comment]
awesome-rust is very good - I wasn't aware of it. I wonder if it's best to reference that and keep LBORB for online (md)book format resources?

**Comment by danipoma** [comment]
May be an option. Their learning section seems to contain practices for rust, not necessarily how-tos building things with rust. Don't know if it is deliberate or PR for these tutorials weren't just posted yet.

**Comment by glyn** [comment]
@danipoma If you feel like submitting a PR for this issue or any of the others you raised, that would be great!

**Comment by glyn** [comment]
> May be an option. Their learning section seems to contain practices for rust, not necessarily how-tos building things with rust. Don't know if it is deliberate or PR for these tutorials weren't just posted yet.

You could test the water by sending them a PR. ;-)

**Comment by danipoma** [comment]
> 

I could and maybe I will try to do so. But it might be kinda sad to see that information contained within lborb would get pushed into their repo. Theoretically then this book wouldn't need to exist. Kinda "sad" talking about it if you know what I mean.

**Comment by glyn** [comment]
I think this book still has a purpose - to be a collection of primarily mdbook format books. I really like this format and I think others do to. So I would be comfortable duplicating entries with awesome-rust. If they want to be a catch-all, it's up to them. Or we could send them a PR pointing here so they don't feel the need to list all the mdbooks.

**Comment by glyn** [comment]
I was suggesting raising PR(s) for the non-book resources you have found so we don't need to bother including them here.

**Comment by danipoma** [comment]
> awesome-rust is very good - I wasn't aware of it. I wonder if it's best to reference that and keep LBORB for online (md)book format resources?

> I think this book still has a purpose - to be a collection of primarily mdbook format books. I really like this format and I think others do to. So I would be comfortable duplicating entries with awesome-rust. If they want to be a catch-all, it's up to them. Or we could send them a PR pointing here so they don't feel the need to list all the mdbooks.

I didn't expect you were not aware of it. It is kinda like big index of things for languages and someone did [awesome of awesomeness](https://github.com/bayandin/awesome-awesomeness) - index of awesome indexes.

You might find some interesting topics there for your lborb as well.

**Comment by danipoma** [comment]
Closing since this issue as it was discussed that lborb is for books in mdBook format.
