### ISSUE TITLE
Host some single page .md guides as part of `lborb`?

### ISSUE THREAD

**Issue by kwfn** [lborb/book#71]
Recently there were add some helpful documents such as [Pointers](https://github.com/diwic/reffers-rs/blob/master/docs/Pointers.md). I wonder if some of these single paged books, where they are appropriately licensed, might be forked and merged into `lborb`?

**Comment by glyn** [comment]
I'd really like to avoid lborb including content as that would diverge from the original philosophy of being a handy place to find Rust books you'd not come across. Also, if we included content, we'd be responsible for maintaining it.

Sorry, but closing this issue on the basis of scope creep.
