### ISSUE TITLE
Fix Plotly url 

### ISSUE THREAD

**Issue by gwenn** [lborb/book#82]
https://github.com/lborb/book/blob/af9997c10e4edb2223d57a664bd032c08a4fb032/src/applications.md?plain=1#L38
doesn't work anymore.
Maybe use https://plotly.github.io/plotly.rs/content/getting_started.html instead ?

**Comment by glyn** [comment]
Thanks for reporting this. I'm AFK, but will fix it on my return. Feel free
to provide a PR.
